logo_title: 恶魔萝莉控

style: white

favicon: /favicon.png

menu:
  归档: /archives
  网盘: https://pan.imgblz.cn
  关于: /about
  首页: https://imgblz.cn

valine:
  enable: false
  appId: CaQKuPQDfnfPFUkTw6MMt8ME-gzGzoHsz
  appKey: uWuwGS1xiIwh3zHKENc7ubyL

highlight:
  enable: true

cdn:
  enabled: true
  url: https://cdn.jsdelivr.net/gh/15601560/15601560.github.io@main
